name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Change dir and generate node_modules
        run: |
          cd ./api
          npm i
          git checkout -- .

      - name: Publish package
        run: npx jsr publish
